/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MK22FN512xxx12
package_id: MK22FN512VDC12
mcu_data: ksdk2_0
processor_version: 9.0.0
pin_labels:
- {pin_num: L9, pin_signal: PTA15/SPI0_SCK/UART0_RX/I2S0_RXD0, label: RED_R_R, identifier: RED_R_R}
- {pin_num: H10, pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/I2S0_MCLK, label: RED_R_L, identifier: RED_R_L}
- {pin_num: J10, pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/I2S0_RX_FS, label: RED_R_R_BREAK, identifier: RED_R_R_BREAK}
- {pin_num: F10, pin_signal: PTB20/FB_AD31/CMP0_OUT, label: RED_R_L_BREAK, identifier: RED_R_L_BREAK}
- {pin_num: A7, pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, label: GREEN_F_L, identifier: GREEN_F_L}
- {pin_num: D6, pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, label: RED_F_L, identifier: RED_F_L}
- {pin_num: C6, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, label: BLUE_F_L, identifier: BLUE_F_L}
- {pin_num: C5, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, label: GREEN_F_R, identifier: GREEN_F_R}
- {pin_num: C3, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/LPUART0_RX/I2C0_SCL, label: RED_F_R, identifier: RED_F_R}
- {pin_num: B3, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/LPUART0_TX/I2C0_SDA, label: BLUE_F_R, identifier: BLUE_F_R}
- {pin_num: K7, pin_signal: PTA5/USB_CLKIN/FTM0_CH2/I2S0_TX_BCLK/JTAG_TRST_b, label: IMU_INT, identifier: IMU_INT}
- {pin_num: H5, pin_signal: ADC0_SE17/PTE24/I2C0_SCL/EWM_OUT_b, label: I2C_SCL, identifier: I2C_SCL}
- {pin_num: J5, pin_signal: ADC0_SE18/PTE25/I2C0_SDA/EWM_IN, label: I2C_SDA, identifier: I2C_SDA}
- {pin_num: B8, pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK/LPUART0_RX, label: COL_SEN_INT, identifier: COL_SEN_INT}
- {pin_num: B6, pin_signal: PTC12/FB_AD27/FTM3_FLT0, label: COL_SEN_LED_W, identifier: COL_SEN_LED_W}
- {pin_num: H6, pin_signal: PTE26/CLKOUT32K/RTC_CLKOUT/USB_CLKIN, label: NRES_DISP, identifier: NRES_DISP}
- {pin_num: G11, pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA, label: RIGHT, identifier: RIGHT}
- {pin_num: G10, pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB, label: DOWN, identifier: DOWN}
- {pin_num: G9, pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT3, label: UP, identifier: UP}
- {pin_num: E10, pin_signal: PTB9/SPI1_PCS1/LPUART0_CTS_b/FB_AD20, label: PUSH, identifier: PUSH;LEFT}
- {pin_num: G8, pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0, label: PUSH, identifier: PUSH}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    LED();
    JOYSTICK();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: H5, peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE17/PTE24/I2C0_SCL/EWM_OUT_b}
  - {pin_num: J5, peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE18/PTE25/I2C0_SDA/EWM_IN}
  - {pin_num: K7, peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/USB_CLKIN/FTM0_CH2/I2S0_TX_BCLK/JTAG_TRST_b, direction: INPUT}
  - {pin_num: B8, peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK/LPUART0_RX, direction: INPUT}
  - {pin_num: B6, peripheral: GPIOC, signal: 'GPIO, 12', pin_signal: PTC12/FB_AD27/FTM3_FLT0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: H6, peripheral: GPIOE, signal: 'GPIO, 26', pin_signal: PTE26/CLKOUT32K/RTC_CLKOUT/USB_CLKIN, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t IMU_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA5 (pin K7)  */
    GPIO_PinInit(BOARD_INITPINS_IMU_INT_GPIO, BOARD_INITPINS_IMU_INT_PIN, &IMU_INT_config);

    gpio_pin_config_t COL_SEN_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin B8)  */
    GPIO_PinInit(BOARD_INITPINS_COL_SEN_INT_GPIO, BOARD_INITPINS_COL_SEN_INT_PIN, &COL_SEN_INT_config);

    gpio_pin_config_t COL_SEN_LED_W_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC12 (pin B6)  */
    GPIO_PinInit(BOARD_INITPINS_COL_SEN_LED_W_GPIO, BOARD_INITPINS_COL_SEN_LED_W_PIN, &COL_SEN_LED_W_config);

    gpio_pin_config_t NRES_DISP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE26 (pin H6)  */
    GPIO_PinInit(BOARD_INITPINS_NRES_DISP_GPIO, BOARD_INITPINS_NRES_DISP_PIN, &NRES_DISP_config);

    /* PORTA5 (pin K7) is configured as PTA5 */
    PORT_SetPinMux(BOARD_INITPINS_IMU_INT_PORT, BOARD_INITPINS_IMU_INT_PIN, kPORT_MuxAsGpio);

    /* PORTC12 (pin B6) is configured as PTC12 */
    PORT_SetPinMux(BOARD_INITPINS_COL_SEN_LED_W_PORT, BOARD_INITPINS_COL_SEN_LED_W_PIN, kPORT_MuxAsGpio);

    /* PORTC3 (pin B8) is configured as PTC3 */
    PORT_SetPinMux(BOARD_INITPINS_COL_SEN_INT_PORT, BOARD_INITPINS_COL_SEN_INT_PIN, kPORT_MuxAsGpio);

    /* PORTE24 (pin H5) is configured as I2C0_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SCL_PORT, BOARD_INITPINS_I2C_SCL_PIN, kPORT_MuxAlt5);

    /* PORTE25 (pin J5) is configured as I2C0_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SDA_PORT, BOARD_INITPINS_I2C_SDA_PIN, kPORT_MuxAlt5);

    /* PORTE26 (pin H6) is configured as PTE26 */
    PORT_SetPinMux(BOARD_INITPINS_NRES_DISP_PORT, BOARD_INITPINS_NRES_DISP_PIN, kPORT_MuxAsGpio);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LED:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D6, peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/FTM2_FLT0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: A7, peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: C6, peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: C3, peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/LPUART0_RX/I2C0_SCL, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: C5, peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: B3, peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/LPUART0_TX/I2C0_SDA, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: H10, peripheral: GPIOA, signal: 'GPIO, 17', pin_signal: ADC1_SE17/PTA17/SPI0_SIN/UART0_RTS_b/I2S0_MCLK, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: L9, peripheral: GPIOA, signal: 'GPIO, 15', pin_signal: PTA15/SPI0_SCK/UART0_RX/I2S0_RXD0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: F10, peripheral: GPIOB, signal: 'GPIO, 20', pin_signal: PTB20/FB_AD31/CMP0_OUT, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: J10, peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: PTA16/SPI0_SOUT/UART0_CTS_b/I2S0_RX_FS, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LED
 * Description   : All MC Car LEDs
 *
 * END ****************************************************************************************************************/
void LED(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    gpio_pin_config_t RED_R_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA15 (pin L9)  */
    GPIO_PinInit(LED_RED_R_R_GPIO, LED_RED_R_R_PIN, &RED_R_R_config);

    gpio_pin_config_t RED_R_R_BREAK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA16 (pin J10)  */
    GPIO_PinInit(LED_RED_R_R_BREAK_GPIO, LED_RED_R_R_BREAK_PIN, &RED_R_R_BREAK_config);

    gpio_pin_config_t RED_R_L_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA17 (pin H10)  */
    GPIO_PinInit(LED_RED_R_L_GPIO, LED_RED_R_L_PIN, &RED_R_L_config);

    gpio_pin_config_t RED_R_L_BREAK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB20 (pin F10)  */
    GPIO_PinInit(LED_RED_R_L_BREAK_GPIO, LED_RED_R_L_BREAK_PIN, &RED_R_L_BREAK_config);

    gpio_pin_config_t GREEN_F_L_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC8 (pin A7)  */
    GPIO_PinInit(LED_GREEN_F_L_GPIO, LED_GREEN_F_L_PIN, &GREEN_F_L_config);

    gpio_pin_config_t RED_F_L_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin D6)  */
    GPIO_PinInit(LED_RED_F_L_GPIO, LED_RED_F_L_PIN, &RED_F_L_config);

    gpio_pin_config_t BLUE_F_L_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC10 (pin C6)  */
    GPIO_PinInit(LED_BLUE_F_L_GPIO, LED_BLUE_F_L_PIN, &BLUE_F_L_config);

    gpio_pin_config_t GREEN_F_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC11 (pin C5)  */
    GPIO_PinInit(LED_GREEN_F_R_GPIO, LED_GREEN_F_R_PIN, &GREEN_F_R_config);

    gpio_pin_config_t RED_F_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin C3)  */
    GPIO_PinInit(LED_RED_F_R_GPIO, LED_RED_F_R_PIN, &RED_F_R_config);

    gpio_pin_config_t BLUE_F_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin B3)  */
    GPIO_PinInit(LED_BLUE_F_R_GPIO, LED_BLUE_F_R_PIN, &BLUE_F_R_config);

    /* PORTA15 (pin L9) is configured as PTA15 */
    PORT_SetPinMux(LED_RED_R_R_PORT, LED_RED_R_R_PIN, kPORT_MuxAsGpio);

    /* PORTA16 (pin J10) is configured as PTA16 */
    PORT_SetPinMux(LED_RED_R_R_BREAK_PORT, LED_RED_R_R_BREAK_PIN, kPORT_MuxAsGpio);

    /* PORTA17 (pin H10) is configured as PTA17 */
    PORT_SetPinMux(LED_RED_R_L_PORT, LED_RED_R_L_PIN, kPORT_MuxAsGpio);

    /* PORTB20 (pin F10) is configured as PTB20 */
    PORT_SetPinMux(LED_RED_R_L_BREAK_PORT, LED_RED_R_L_BREAK_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin C6) is configured as PTC10 */
    PORT_SetPinMux(LED_BLUE_F_L_PORT, LED_BLUE_F_L_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin C5) is configured as PTC11 */
    PORT_SetPinMux(LED_GREEN_F_R_PORT, LED_GREEN_F_R_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin A7) is configured as PTC8 */
    PORT_SetPinMux(LED_GREEN_F_L_PORT, LED_GREEN_F_L_PIN, kPORT_MuxAsGpio);

    /* PORTC9 (pin D6) is configured as PTC9 */
    PORT_SetPinMux(LED_RED_F_L_PORT, LED_RED_F_L_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin C3) is configured as PTD2 */
    PORT_SetPinMux(LED_RED_F_R_PORT, LED_RED_F_R_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin B3) is configured as PTD3 */
    PORT_SetPinMux(LED_BLUE_F_R_PORT, LED_BLUE_F_R_PIN, kPORT_MuxAsGpio);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
JOYSTICK:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: G11, peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA, direction: INPUT, pull_select: up}
  - {pin_num: G10, peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB, direction: INPUT, pull_select: up}
  - {pin_num: G9, peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT3, direction: INPUT, pull_select: up}
  - {pin_num: E10, peripheral: GPIOB, signal: 'GPIO, 9', pin_signal: PTB9/SPI1_PCS1/LPUART0_CTS_b/FB_AD20, identifier: LEFT, direction: INPUT, pull_select: up}
  - {pin_num: G8, peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/UART0_CTS_b/FTM0_FLT0, direction: INPUT, pull_select: up}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : JOYSTICK
 * Description   : All joystick input pins
 *
 * END ****************************************************************************************************************/
void JOYSTICK(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    gpio_pin_config_t RIGHT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin G11)  */
    GPIO_PinInit(JOYSTICK_RIGHT_GPIO, JOYSTICK_RIGHT_PIN, &RIGHT_config);

    gpio_pin_config_t DOWN_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin G10)  */
    GPIO_PinInit(JOYSTICK_DOWN_GPIO, JOYSTICK_DOWN_PIN, &DOWN_config);

    gpio_pin_config_t UP_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin G9)  */
    GPIO_PinInit(JOYSTICK_UP_GPIO, JOYSTICK_UP_PIN, &UP_config);

    gpio_pin_config_t PUSH_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin G8)  */
    GPIO_PinInit(JOYSTICK_PUSH_GPIO, JOYSTICK_PUSH_PIN, &PUSH_config);

    gpio_pin_config_t LEFT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB9 (pin E10)  */
    GPIO_PinInit(JOYSTICK_LEFT_GPIO, JOYSTICK_LEFT_PIN, &LEFT_config);

    /* PORTB0 (pin G11) is configured as PTB0 */
    PORT_SetPinMux(JOYSTICK_RIGHT_PORT, JOYSTICK_RIGHT_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[0] = ((PORTB->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB1 (pin G10) is configured as PTB1 */
    PORT_SetPinMux(JOYSTICK_DOWN_PORT, JOYSTICK_DOWN_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[1] = ((PORTB->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB2 (pin G9) is configured as PTB2 */
    PORT_SetPinMux(JOYSTICK_UP_PORT, JOYSTICK_UP_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[2] = ((PORTB->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB3 (pin G8) is configured as PTB3 */
    PORT_SetPinMux(JOYSTICK_PUSH_PORT, JOYSTICK_PUSH_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[3] = ((PORTB->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB9 (pin E10) is configured as PTB9 */
    PORT_SetPinMux(JOYSTICK_LEFT_PORT, JOYSTICK_LEFT_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[9] = ((PORTB->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
