/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE24 (coord H5), I2C_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SCL_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SCL_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SCL_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE25 (coord J5), I2C_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SDA_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SDA_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SDA_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA5 (coord K7), IMU_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IMU_INT_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IMU_INT_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IMU_INT_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IMU_INT_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IMU_INT_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC3 (coord B8), COL_SEN_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_COL_SEN_INT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_COL_SEN_INT_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_COL_SEN_INT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_COL_SEN_INT_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_COL_SEN_INT_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTC12 (coord B6), COL_SEN_LED_W
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_COL_SEN_LED_W_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_COL_SEN_LED_W_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_COL_SEN_LED_W_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_COL_SEN_LED_W_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_COL_SEN_LED_W_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTE26 (coord H6), NRES_DISP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NRES_DISP_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NRES_DISP_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_NRES_DISP_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_NRES_DISP_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NRES_DISP_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTC9 (coord D6), RED_F_L
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_F_L_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LED_RED_F_L_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_RED_F_L_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LED_RED_F_L_PIN 9U                   /*!<@brief PORT pin number */
#define LED_RED_F_L_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC8 (coord A7), GREEN_F_L
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_GREEN_F_L_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LED_GREEN_F_L_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_GREEN_F_L_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LED_GREEN_F_L_PIN 8U                   /*!<@brief PORT pin number */
#define LED_GREEN_F_L_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTC10 (coord C6), BLUE_F_L
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_BLUE_F_L_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LED_BLUE_F_L_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_BLUE_F_L_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LED_BLUE_F_L_PIN 10U                   /*!<@brief PORT pin number */
#define LED_BLUE_F_L_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTD2 (coord C3), RED_F_R
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_F_R_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define LED_RED_F_R_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_RED_F_R_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define LED_RED_F_R_PIN 2U                   /*!<@brief PORT pin number */
#define LED_RED_F_R_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC11 (coord C5), GREEN_F_R
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_GREEN_F_R_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LED_GREEN_F_R_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_GREEN_F_R_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LED_GREEN_F_R_PIN 11U                   /*!<@brief PORT pin number */
#define LED_GREEN_F_R_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTD3 (coord B3), BLUE_F_R
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_BLUE_F_R_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define LED_BLUE_F_R_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_BLUE_F_R_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define LED_BLUE_F_R_PIN 3U                   /*!<@brief PORT pin number */
#define LED_BLUE_F_R_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTA17 (coord H10), RED_R_L
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_R_L_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define LED_RED_R_L_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_RED_R_L_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define LED_RED_R_L_PIN 17U                   /*!<@brief PORT pin number */
#define LED_RED_R_L_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTA15 (coord L9), RED_R_R
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_R_R_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define LED_RED_R_R_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_RED_R_R_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define LED_RED_R_R_PIN 15U                   /*!<@brief PORT pin number */
#define LED_RED_R_R_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTB20 (coord F10), RED_R_L_BREAK
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_R_L_BREAK_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define LED_RED_R_L_BREAK_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_RED_R_L_BREAK_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define LED_RED_R_L_BREAK_PIN 20U                   /*!<@brief PORT pin number */
#define LED_RED_R_L_BREAK_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTA16 (coord J10), RED_R_R_BREAK
  @{ */

/* Symbols to be used with GPIO driver */
#define LED_RED_R_R_BREAK_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define LED_RED_R_R_BREAK_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LED_RED_R_R_BREAK_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define LED_RED_R_R_BREAK_PIN 16U                   /*!<@brief PORT pin number */
#define LED_RED_R_R_BREAK_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief All MC Car LEDs
 *
 */
void LED(void);

/*! @name PORTB0 (coord G11), RIGHT
  @{ */

/* Symbols to be used with GPIO driver */
#define JOYSTICK_RIGHT_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define JOYSTICK_RIGHT_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define JOYSTICK_RIGHT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define JOYSTICK_RIGHT_PIN 0U                   /*!<@brief PORT pin number */
#define JOYSTICK_RIGHT_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTB1 (coord G10), DOWN
  @{ */

/* Symbols to be used with GPIO driver */
#define JOYSTICK_DOWN_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define JOYSTICK_DOWN_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define JOYSTICK_DOWN_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define JOYSTICK_DOWN_PIN 1U                   /*!<@brief PORT pin number */
#define JOYSTICK_DOWN_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB2 (coord G9), UP
  @{ */

/* Symbols to be used with GPIO driver */
#define JOYSTICK_UP_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define JOYSTICK_UP_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define JOYSTICK_UP_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define JOYSTICK_UP_PIN 2U                   /*!<@brief PORT pin number */
#define JOYSTICK_UP_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB9 (coord E10), LEFT
  @{ */

/* Symbols to be used with GPIO driver */
#define JOYSTICK_LEFT_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define JOYSTICK_LEFT_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define JOYSTICK_LEFT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define JOYSTICK_LEFT_PIN 9U                   /*!<@brief PORT pin number */
#define JOYSTICK_LEFT_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB3 (coord G8), PUSH
  @{ */

/* Symbols to be used with GPIO driver */
#define JOYSTICK_PUSH_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define JOYSTICK_PUSH_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define JOYSTICK_PUSH_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define JOYSTICK_PUSH_PIN 3U                   /*!<@brief PORT pin number */
#define JOYSTICK_PUSH_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*!
 * @brief All joystick input pins
 *
 */
void JOYSTICK(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
