/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v11.0
processor: MK22FN512xxx12
package_id: MK22FN512VDC12
mcu_data: ksdk2_0
processor_version: 11.0.1
pin_labels:
- {pin_num: C6, pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, label: LED_BLUE_F_L, identifier: LED_BLUE_F_L}
- {pin_num: J4, pin_signal: PTA11/FTM2_CH1/FTM2_QD_PHB, label: LED_GREEN_F_R, identifier: LED_GREEN_F_R}
- {pin_num: C5, pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, label: LED_GREEN_F_R, identifier: LED_GREEN_F_R}
- {pin_num: A7, pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, label: LED_GREEN_F_L, identifier: LED_GREEN_F_L}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C6, peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5, direction: OUTPUT}
  - {pin_num: C5, peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/FB_RW_b, direction: OUTPUT}
  - {pin_num: A7, peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);

    gpio_pin_config_t LED_GREEN_F_L_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC8 (pin A7)  */
    GPIO_PinInit(BOARD_INITPINS_LED_GREEN_F_L_GPIO, BOARD_INITPINS_LED_GREEN_F_L_PIN, &LED_GREEN_F_L_config);

    gpio_pin_config_t LED_BLUE_F_L_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC10 (pin C6)  */
    GPIO_PinInit(BOARD_INITPINS_LED_BLUE_F_L_GPIO, BOARD_INITPINS_LED_BLUE_F_L_PIN, &LED_BLUE_F_L_config);

    gpio_pin_config_t LED_GREEN_F_R_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC11 (pin C5)  */
    GPIO_PinInit(BOARD_INITPINS_LED_GREEN_F_R_GPIO, BOARD_INITPINS_LED_GREEN_F_R_PIN, &LED_GREEN_F_R_config);

    /* PORTC10 (pin C6) is configured as PTC10 */
    PORT_SetPinMux(BOARD_INITPINS_LED_BLUE_F_L_PORT, BOARD_INITPINS_LED_BLUE_F_L_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin C5) is configured as PTC11 */
    PORT_SetPinMux(BOARD_INITPINS_LED_GREEN_F_R_PORT, BOARD_INITPINS_LED_GREEN_F_R_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin A7) is configured as PTC8 */
    PORT_SetPinMux(BOARD_INITPINS_LED_GREEN_F_L_PORT, BOARD_INITPINS_LED_GREEN_F_L_PIN, kPORT_MuxAsGpio);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
