/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC10 (coord C6), LED_BLUE_F_L
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BLUE_F_L_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_F_L_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_F_L_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_F_L_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_F_L_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTC11 (coord C5), LED_GREEN_F_R
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_F_R_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_F_R_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_F_R_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_F_R_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_F_R_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC8 (coord A7), LED_GREEN_F_L
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_F_L_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_F_L_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_F_L_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_F_L_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_F_L_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
